config/routes.rb
Rails.application.routes.draw do
  resources :articles

  get 'order/new'

  resources :line_items

  resources :bcarts

  get 'users/new'
get 'page/cart'
  get 'page/home'
  get 'page/pay'
  
  root  'page#home'
  resources :users
  match '/signup',  to: 'users#new',            via: 'get'
  resources :sessions, only: [:new, :create, :destroy]
  match '/signin',  to: 'sessions#new',         via: 'get'
  match '/signout', to: 'sessions#destroy',     via: 'delete'

  resources :carts
  get 'carts/show'
   
  resources :products
  get 'products/show'
  get 'products/new'
  match '/add',  to: 'products#create',            via: 'post'
   
  resources :bsessions, only: [:new, :create]
  resources :email, only: [:new, :create, :destroy]
  resources :bcarts, only: [:new, :create, :destroy, :show]
  get 'bcarts/show'
  match '/bcart' ,to: 'bcarts#show', via: 'get'
  resources :order, only: [:new, :create, :destroy]
  
  
  










end

app/models/article.rb
class Article < ActiveRecord::Base
 
  validates :title, presence: true, uniqueness: true
  validates :content, presence: true
 
  # It returns the articles whose titles contain one or more words that form the query
  def self.search(query)
    # where(:title, query) -> This would return an exact match of the query
    where("title like ?", "%#{query}%") 
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:show, :edit, :update, :destroy]

  # GET /articles
  # GET /articles.json
  def index
     if params[:search]
      #@articles = Product.search(params[:search]).order("created_at DESC")
      search =Product.search{
        fulltext params[:search]
        paginate :page => params[:page].present? ? params[:page] :1 , :per_page => 5
      }
     @articles = search.results
    else
      @articles = Product.order("created_at DESC")
    end
  end

  # GET /articles/1
  # GET /articles/1.json
  def show
  end

  # GET /articles/new
  def new
    @article = Article.new
  end

  # GET /articles/1/edit
  def edit
  end

  # POST /articles
  # POST /articles.json
  def create
    @article = Article.new(article_params)

    respond_to do |format|
      if @article.save
        format.html { redirect_to @article, notice: 'Article was successfully created.' }
        format.json { render :show, status: :created, location: @article }
      else
        format.html { render :new }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /articles/1
  # PATCH/PUT /articles/1.json
  def update
    respond_to do |format|
      if @article.update(article_params)
        format.html { redirect_to @article, notice: 'Article was successfully updated.' }
        format.json { render :show, status: :ok, location: @article }
      else
        format.html { render :edit }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /articles/1
  # DELETE /articles/1.json
  def destroy
    @article.destroy
    respond_to do |format|
      format.html { redirect_to articles_url, notice: 'Article was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_article
      @article = Article.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def article_params
      params.require(:article).permit(:title, :content)
    end
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/_form.html.erb
<%= form_for(@article) do |f| %>
  <% if @article.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@article.errors.count, "error") %> prohibited this article from being saved:</h2>

      <ul>
      <% @article.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :content %><br>
    <%= f.text_field :content %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/articles/edit.html.erb
<h1>Editing article</h1>

<%= render 'form' %>

<%= link_to 'Show', @article %> |
<%= link_to 'Back', articles_path %>

app/views/articles/index.html.erb
<div class="row">
<div class="span6">

<% @articles.each do |article| %>
  <div class="article">
    <h3 class="article-title"><%=article.name %></h3>
  <%= link_to article, id: "logo-p" do %>
                      <img src="<%=article.img%>" alt="img"  width="300" height="300">
                    
 <% end %>

</div>

<% end %>
<%= will_paginate @articles%>
</div>
</div>

app/views/articles/new.html.erb
<h1>New article</h1>

<%= render 'form' %>

<%= link_to 'Back', articles_path %>

app/views/articles/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @article.title %>
</p>

<p>
  <strong>Content:</strong>
  <%= @article.content %>
</p>

<%= link_to 'Edit', edit_article_path(@article) %> |
<%= link_to 'Back', articles_path %>