config/routes.rb
Rails.application.routes.draw do
  resources :articles

  get 'order/new'

  resources :line_items

  resources :bcarts

  get 'users/new'
get 'page/cart'
  get 'page/home'
  get 'page/pay'
  
  root  'page#home'
  resources :users
  match '/signup',  to: 'users#new',            via: 'get'
  resources :sessions, only: [:new, :create, :destroy]
  match '/signin',  to: 'sessions#new',         via: 'get'
  match '/signout', to: 'sessions#destroy',     via: 'delete'

  resources :carts
  get 'carts/show'
   
  resources :products
  get 'products/show'
  get 'products/new'
  match '/add',  to: 'products#create',            via: 'post'
   
  resources :bsessions, only: [:new, :create]
  resources :email, only: [:new, :create, :destroy]
  resources :bcarts, only: [:new, :create, :destroy, :show]
  get 'bcarts/show'
  match '/bcart' ,to: 'bcarts#show', via: 'get'
  resources :order, only: [:new, :create, :destroy]
  
  
  










end

app/controllers/bcarts_controller.rb
class BcartsController < ApplicationController
  before_action :set_bcart, only: [:show, :edit, :update, :destroy]

  # GET /bcarts
  # GET /bcarts.json
  def index
    @bcarts = Bcart.all
  end

  # GET /bcarts/1
  # GET /bcarts/1.json
  def show
  if session[:bcart_id] != nil
  @bcart = Bcart.find(session[:bcart_id])
  else
  redirect_to root_url, :notice => 'Invalid cart or your cart is   empty'
  end
  begin
  #@bcart = Bcart.find(params[:id])
  rescue ActiveRecord::RecordNotFound
  logger.error "invalid cart #{params[:id]}"
  redirect_to root_url, :notice => 'Invalid cart or your cart is   empty'
  
  end
  end

  # GET /bcarts/new
  def new
    @bcart = Bcart.new
  end

  # GET /bcarts/1/edit
  def edit
  end

  # POST /bcarts
  # POST /bcarts.json
  def create
    @bcart = Bcart.new(bcart_params)

    respond_to do |format|
      if @bcart.save
        format.html { redirect_to @bcart, notice: 'Bcart was successfully created.' }
        format.json { render :show, status: :created, location: @bcart }
      else
        format.html { render :new }
        format.json { render json: @bcart.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /bcarts/1
  # PATCH/PUT /bcarts/1.json
  def update
    respond_to do |format|
      if @bcart.update(bcart_params)
        format.html { redirect_to @bcart, notice: 'Bcart was successfully updated.' }
        format.json { render :show, status: :ok, location: @bcart }
      else
        format.html { render :edit }
        format.json { render json: @bcart.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bcarts/1
  # DELETE /bcarts/1.json
  def destroy
       @bcart = Bcart.find(params[:id])
       @bcart.destroy
       session[:bcart_id] = nil
     
     respond_to do |format|
      format.html { redirect_to root_url, notice: 'Bcart was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_bcart
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def bcart_params
      params[:bcart]
    end
end

app/helpers/bcarts_helper.rb
module BcartsHelper
end

app/views/bcarts/_bcart.html.erb
<div class="cart_title">YOUR CART</div>
<table>
<%= render(bcart.line_items) %>
<tr class="total_line">
<td colspan="2">TOTAL</td>
<td class="total_cell"><%= number_to_currency(bcart.total_price) %></td>
</tr>
</table>

app/views/bcarts/_form.html.erb
<%= form_for(@bcart) do |f| %>
  <% if @bcart.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@bcart.errors.count, "error") %> prohibited this bcart from being saved:</h2>

      <ul>
      <% @bcart.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/bcarts/edit.html.erb
<h1>Editing bcart</h1>

<%= render 'form' %>

<%= link_to 'Show', @bcart %> |
<%= link_to 'Back', bcarts_path %>

app/views/bcarts/index.html.erb
<h1>Listing bcarts</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @bcarts.each do |bcart| %>
      <tr>
        <td><%= link_to 'Show', bcart %></td>
        <td><%= link_to 'Edit', edit_bcart_path(bcart) %></td>
        <td><%= link_to 'Destroy', bcart, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Bcart', new_bcart_path %>

app/views/bcarts/new.html.erb
<h1>New bcart</h1>

<%= render 'form' %>

<%= link_to 'Back', bcarts_path %>

app/views/bcarts/show.html.erb
<div class="container">
<div class="row" >
<div class="span6 ">
<ul>
<% for item in @bcart.line_items %>
<li><%= item.product.name %>-<%="Quantity: #{item.quantity}"%>-<%= number_to_currency(item.total_price)%>---<%=link_to "details", item.product%> 
<%= button_to 'delete', item, :method => :delete,class: "btn btn-default",:confirm => 'Are you sure?' %>

</li>
<% end %>
</ul>

<h2>TOTAL: <%=number_to_currency(@bcart.total_price)%></h2>
<br>
<br>
<%= button_to 'REMOVE CART', @bcart,class: "btn btn-danger bcart-show1", :method => :delete,
:confirm => 'Are you sure?' %>
</div>
<div class = "span3 ">
  <h4>CONFIRM YOU CART?</h4>
     <% b = "WELCOME TO DEDO VENSHOP\n 
             YOUR ORDER CONTAINS : \n" %>
    <% if @bcart.line_items.count == 0%>
      <% $check = false %>
      <%else%>
      <% $check = true%>
    <% end%>
    <% for item in @bcart.line_items %>
       <% b = b + item.product.name+ " -- " + item.quantity.to_s + "\n" %>
    <% end %>
    <% b = b + "TOTAL: " + @bcart.total_price.to_s+ "$" %>
    <%= form_for(:order, url: order_index_path) do |f| %>
       <%= f.hidden_field :body, :value => b%>

     <%= f.submit "CONFIRM", class: "btn btn-large btn-primary bcart-show2"    %>
    <% end %>

</div>
</div>
</div>