config/routes.rb
Rails.application.routes.draw do
  resources :articles

  get 'order/new'

  resources :line_items

  resources :bcarts

  get 'users/new'
get 'page/cart'
  get 'page/home'
  get 'page/pay'
  
  root  'page#home'
  resources :users
  match '/signup',  to: 'users#new',            via: 'get'
  resources :sessions, only: [:new, :create, :destroy]
  match '/signin',  to: 'sessions#new',         via: 'get'
  match '/signout', to: 'sessions#destroy',     via: 'delete'

  resources :carts
  get 'carts/show'
   
  resources :products
  get 'products/show'
  get 'products/new'
  match '/add',  to: 'products#create',            via: 'post'
   
  resources :bsessions, only: [:new, :create]
  resources :email, only: [:new, :create, :destroy]
  resources :bcarts, only: [:new, :create, :destroy, :show]
  get 'bcarts/show'
  match '/bcart' ,to: 'bcarts#show', via: 'get'
  resources :order, only: [:new, :create, :destroy]
  
  
  










end

app/models/article.rb
class Article < ActiveRecord::Base
 
  validates :title, presence: true, uniqueness: true
  validates :content, presence: true
 
  # It returns the articles whose titles contain one or more words that form the query
  def self.search(query)
    # where(:title, query) -> This would return an exact match of the query
    where("title like ?", "%#{query}%") 
  end
end

app/models/product.rb
class Product < ActiveRecord::Base
      validates :name,presence: true
      validates :price,presence: true
      validates :cart_id,presence: true
      validates :desc,presence: true
 	belongs_to :cart
     has_many :line_items
 

  searchable do
  text :name,:desc
  integer :id	
  end

 def self.nsearch(query)
 	#
    # where(:title, query) -> This would return an exact match of the query
    #where("name like ?", "%#{query}%") 
  end
end

app/controllers/bcarts_controller.rb
class BcartsController < ApplicationController
  before_action :set_bcart, only: [:show, :edit, :update, :destroy]

  # GET /bcarts
  # GET /bcarts.json
  def index
    @bcarts = Bcart.all
  end

  # GET /bcarts/1
  # GET /bcarts/1.json
  def show
  if session[:bcart_id] != nil
  @bcart = Bcart.find(session[:bcart_id])
  else
  redirect_to root_url, :notice => 'Invalid cart or your cart is   empty'
  end
  begin
  #@bcart = Bcart.find(params[:id])
  rescue ActiveRecord::RecordNotFound
  logger.error "invalid cart #{params[:id]}"
  redirect_to root_url, :notice => 'Invalid cart or your cart is   empty'
  
  end
  end

  # GET /bcarts/new
  def new
    @bcart = Bcart.new
  end

  # GET /bcarts/1/edit
  def edit
  end

  # POST /bcarts
  # POST /bcarts.json
  def create
    @bcart = Bcart.new(bcart_params)

    respond_to do |format|
      if @bcart.save
        format.html { redirect_to @bcart, notice: 'Bcart was successfully created.' }
        format.json { render :show, status: :created, location: @bcart }
      else
        format.html { render :new }
        format.json { render json: @bcart.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /bcarts/1
  # PATCH/PUT /bcarts/1.json
  def update
    respond_to do |format|
      if @bcart.update(bcart_params)
        format.html { redirect_to @bcart, notice: 'Bcart was successfully updated.' }
        format.json { render :show, status: :ok, location: @bcart }
      else
        format.html { render :edit }
        format.json { render json: @bcart.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bcarts/1
  # DELETE /bcarts/1.json
  def destroy
       @bcart = Bcart.find(params[:id])
       @bcart.destroy
       session[:bcart_id] = nil
     
     respond_to do |format|
      format.html { redirect_to root_url, notice: 'Bcart was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_bcart
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def bcart_params
      params[:bcart]
    end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
	def show
		@cart = Cart.find(params[:id])
           @products=@cart.products
	end
end

app/controllers/email_controller.rb
class EmailController < ApplicationController
  def new
      
  end 

   def create
 if params[:email][:name].empty? | params[:email][:email].empty?
       flash[:error] = " Please type your name and email"
       redirect_to root_path
 else  
      
@content="Hi #{params[:email][:name]},\n" +params[:email][:body]
        ActionMailer::Base.mail(:from => "rewandedo1009@gmail.com", :to => params[:email][:email], :subject => "DEDO VENSHOP ORDERS", :body => @content).deliver
      flash[:success] = "Email sent, please check it out" 
      redirect_to root_path
   end    
   end
end

app/controllers/order_controller.rb
class OrderController < ApplicationController
  def new
  end
  def create
      if $check == true
           @body = params[:order][:body]
            render 'new'
      else 
        flash[:error] = "Nothing in your card , dont make an useless email"
        redirect_to :back    
       
      end
  end
end

app/controllers/page_controller.rb
class PageController < ApplicationController
  def home
    @carts = Cart.all
    @lp =Product.paginate(:page => params[:page], :per_page => 10)
     # bcart = Bcart.find(session[:bcart_id]
   # @count = bcart.line_items.count
   @bcart = current_bcart
  end

  def cart
  end

  def page
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
  	@user = User.new
  end
  
  def show
  	@user = User.find(params[:id])
  end
  def edit
   @user = User.find(params[:id])
  end
  def update
    @user = User.find(params[:id])
    if @user.update_attributes(user_params)
      flash[:success] = "Profile updated"
      redirect_to @user
    else
      
      render 'edit'
    end
  end
   def create
    @user = User.new(user_params)
    if @user.save
     sign_in @user
    	flash[:success] = "Welcome #{@user.name} to DEDO VENSHOP"
      
      redirect_to @user
    else
      render 'new'
    end
  end

  private

    def user_params
      params.require(:user).permit(:name, :email, :password,
                                   :password_confirmation)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper

	def full_title(page_title)
    base_title = "Dedo VenShop"
    if page_title.empty?
      base_title
    else
      "#{base_title} | #{page_title}"
    end
  end
    
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/bcarts_helper.rb
module BcartsHelper
end

app/helpers/bsessions_helper.rb
module BsessionsHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/email_helper.rb
module EmailHelper
end

app/helpers/line_items_helper.rb
module LineItemsHelper
end

app/helpers/order_helper.rb
module OrderHelper
end

app/helpers/page_helper.rb
module PageHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
	def sign_in(user)
    remember_token = User.new_remember_token
    cookies.permanent[:remember_token] = remember_token
    user.update_attribute(:remember_token, User.digest(remember_token))
    self.current_user = user
    end
    
    def current_user=(user)
        @current_user = user
    end 
    def current_user
    remember_token = User.digest(cookies[:remember_token])
    @current_user ||= User.find_by(remember_token: remember_token)
    end

    def signed_in?
    !current_user.nil?
    end

    def sign_out
    current_user.update_attribute(:remember_token,
                                  User.digest(User.new_remember_token))
    cookies.delete(:remember_token)
    self.current_user = nil
  end
end

app/helpers/users_helper.rb
module UsersHelper
	def gravatar_for(user)
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end
end

app/views/page/cart.html.erb
<% provide(:title, 'cart') %>
<h1>Page#cart</h1>
<p>Find me in app/views/page/cart.html.erb</p>

app/views/page/home.html.erb
<% provide(:title, 'home') %>
<div>
  <div class="row">
     
    <div id='bcart' class="span4 cart-user">
     <%= render @bcart %>
     <br>
     <%= link_to @bcart, id: "logo-p" do %>
                      <img src="http://www.graphicsbeam.com/wp-content/uploads/2012/04/Shopping-Cart-Icon-with-PSD-and-PNG-Format.png" alt="img"  width="350" height="350">
                 <% end %>

    </div>

     <div class="span6  showh">
        <ul class="d-ul">
                            <%@lp.each do |p| %>
                   <div class="d-list">
  	              <li><%= link_to p, id: "logo-p" do %>
                      <img src="<%=p.img%>" alt="img"  width="150" height="152">
                 <% end %>
           <%=form_for(:bsession, url: bsessions_path) do |f| %>
                 
                 <%= f.hidden_field :name, :value => p.name%>
                 <%= f.hidden_field :price, :value => p.price%>
                 <%= f.hidden_field :desc, :value => p.desc%>
                 <%= f.hidden_field :img, :value => p.img%>
                 <h2 class="dh2" ><%= p.name%></h2><h2><%=number_to_currency(p.price)%></h2>     
  <h6><%=link_to "details", p %> </h6>
                    <%= f.submit "Buy", class: "btn  btn-default
 bhome" %>  
           <% end %>
<%= button_to 'Add to Cart',line_items_path(:product_id => p),:remote => true,class: "btn btn-danger home"%> 
                   </li>
               </div>
                  <% end %>
                      </ul>
<%= will_paginate @lp%>
        </div>

  </div>
</div>

app/views/page/pay.html.erb
<% provide(:title, 'pay') %>
<h1>Page#page</h1>
<p>Find me in app/views/page/page.html.erb</p>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-error">
      The form contains <%= pluralize(@user.errors.count, "error") %>.
    </div>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li>* <%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>